version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: tuesday
      time: "08:00"
      timezone: "Africa/Nairobi"
    groups:
      detekt:
        patterns:
          - "io.gitlab.arturbosch.detekt*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: tuesday
      time: "08:00"
      timezone: "Africa/Nairobi"